### ISSUE TITLE
mhcflurry-downloads fetch failed

### ISSUE THREAD

**Issue by weipenegHU** [hammerlab/mhcflurry#104] opened 2017-09-29 03:28 UTC
Hi, guys, I am trying to deploy mhcflurry. When I used “”mhcflutty-downloads fetch"  to download the model, it kept prompting connection failed. And I checked this link "http://github.com/hammerlab/mhcflurry/releases/download/0.9.1/“ on my browser, it said the page was not found.

**Comment by timodonnell** [comment] 2017-09-29 13:06
Hi @weipenegHU ,

Can you paste the full error you're seeing when you run `mhcflurry-downloads fetch`? When I go to http://github.com/hammerlab/mhcflurry/releases/download/0.9.1/models_class1.tar.bz2 I am able to download these models so the full error may help see what's up.

Thanks,

Tim

**Comment by timodonnell** [comment] 2017-10-13 16:29
Closing for now, please reopen if still an issue

**Closed by timodonnell** 2017-10-13 16:29 UTC

**Comment by weipenegHU** [comment] 2017-10-16 08:44
Sorry for the delay. The full error :
Using TensorFlow backend.
Fetching 1/5 downloads from release 0.9.1
DOWNLOAD NAME                             ALREADY DOWNLOADED?    WILL DOWNLOAD NOW?    URL
models_class1                             YES                    NO                    http://github.com/hammerlab/mhcflurry/releases/download/0.9.1/models_class1.tar.bz2
data_curated                              NO                     YES                   https://github.com/hammerlab/mhcflurry/releases/download/0.9.1/data_curated.tar.bz2
data_kim2014                              NO                     NO                    http://github.com/hammerlab/mhcflurry/releases/download/0.9.1/data_kim2014.tar.bz2
data_iedb                                 NO                     NO                    https://github.com/hammerlab/mhcflurry/releases/download/0.9.1/data_iedb.tar.bz2
models_class1_experiments1                NO                     NO                    http://github.com/hammerlab/mhcflurry/releases/download/0.9.1/models_class1_experiments1.tar.bz2
Downloading: https://github.com/hammerlab/mhcflurry/releases/download/0.9.1/data_curated.tar.bz2
Traceback (most recent call last):
  File "/hwfssz1/BIGDATA_COMPUTING/software/tools/anaconda/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/hwfssz1/BIGDATA_COMPUTING/software/tools/anaconda/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/hwfssz1/BIGDATA_COMPUTING/software/tools/anaconda/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/hwfssz1/BIGDATA_COMPUTING/software/tools/anaconda/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/hwfssz1/BIGDATA_COMPUTING/software/tools/anaconda/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/hwfssz1/BIGDATA_COMPUTING/software/tools/anaconda/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/hwfssz1/BIGDATA_COMPUTING/software/tools/anaconda/lib/python3.6/http/client.py", line 1392, in connect
    super().connect()
  File "/hwfssz1/BIGDATA_COMPUTING/software/tools/anaconda/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/hwfssz1/BIGDATA_COMPUTING/software/tools/anaconda/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/hwfssz1/BIGDATA_COMPUTING/software/tools/anaconda/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

and when I open https://github.com/hammerlab/mhcflurry/releases/download/0.9.1/ in the browser, it prompted that the page is not found.

**Comment by timodonnell** [comment] 2017-10-16 15:37
This URL, which is what it is trying to download, works for me:

https://github.com/hammerlab/mhcflurry/releases/download/0.9.1/data_curated.tar.bz2

The URL to the parent directory gives me the error you're seeing from
github but I don't believe that URL is intended to work and as far as I
know nothing should relies on it: https://github.com/hammerlab/
mhcflurry/releases/download/0.9.1/

So my best guess is this is a connectivity issue on your end. Can you try
downloading the file manually with a command like:

wget
https://github.com/hammerlab/mhcflurry/releases/download/0.9.1/data_curated.tar.bz2

to see if this is a connectivity issue?

**Comment by weipenegHU** [comment] 2017-10-17 01:09
Using wget can download the data successfully, however the mhcflurry-fetch command gave me the connection error. Is it OK if I run mhcflurry without downloading the data?

**Comment by timodonnell** [comment] 2017-10-17 01:25
hmm that's puzzling. Definitely possible there's something not quite right with how I'm downloading the data, but there's not much I can do at this point without a way to reproduce it on my end.

I see from the output you posted that you have already downloaded the mhcflurry models (models_class1), so, yes, you have everything you need to generate predictions from these models as is.

**Comment by weipenegHU** [comment] 2017-10-17 01:53
all right, thanks.
